name: Check DNS Servers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  check-dns:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run DNS Check Script
        run: |
          python check_dns.py
          
      - name: Force Push Changes
        run: |
          if ! git diff --quiet; then
            # Commit'in size atfedilmesi i癟in kullan覺c覺y覺 ayarla
            git config --local user.name "${{ github.actor }}"
            git config --local user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            
            CURRENT_DATE=$(date -u +'%Y-%m-%d %H:%M:%S %Z')
            git add README.md dns-all-up.json dns-adblock.txt dns-malware-block.txt dns-doh-up.json
            git commit -m "Auto-update DNS list: $CURRENT_DATE "
            git push --force
          else
            echo "No changes found, skipping commit."
          fi
